# Generated by Django 4.0.3 on 2022-03-24 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('artist', models.TextField()),
                ('duration', models.FloatField()),
                ('explicit', models.FloatField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('release_date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('duration_ms', models.FloatField()),
                ('explicit', models.FloatField()),
                ('release_date', models.TextField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euphony.album')),
            ],
        ),
        migrations.CreateModel(
            name='Song_rating',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rating_type', models.BooleanField()),
                ('date', models.TextField()),
                ('song_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='euphony.song')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_rating',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rating_type', models.BooleanField()),
                ('date', models.TextField()),
                ('playlist_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='euphony.playlist')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='euphony.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Album_rating',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rating_type', models.BooleanField()),
                ('date', models.TextField()),
                ('album_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='euphony.album')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
