# Generated by Django 4.0.4 on 2022-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_setting_ext',
            name='music_prefs',
            field=models.TextField(default=''),
        ),
    ]
