# Generated by Django 4.0.3 on 2022-05-01 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('euphony', '0002_user_setting_ext_music_prefs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_setting_ext',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_setting_ext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userExt', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
