# Generated by Django 4.0.3 on 2022-04-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphony', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
