# Generated by Django 4.0.3 on 2022-04-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphony', '0003_playlist_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_rating',
            name='rating_type',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist_rating',
            name='rating_type',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='song_rating',
            name='rating_type',
            field=models.BooleanField(null=True),
        ),
    ]
