# Generated by Django 4.0.3 on 2022-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphony', '0003_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
