# Generated by Django 4.0.3 on 2022-04-20 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphony', '0004_alter_album_rating_rating_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_rating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='playlist_rating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='song_rating',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
