# Generated by Django 4.0.3 on 2022-03-21 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_rating',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rating_type', models.BooleanField()),
                ('date', models.TextField()),
                ('song_id', models.ManyToManyField(to='databases.song')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='playlist_rating',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rating_type', models.BooleanField()),
                ('date', models.TextField()),
                ('playlist_id', models.ManyToManyField(to='databases.playlist')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='album_rating',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rating_type', models.BooleanField()),
                ('date', models.TextField()),
                ('album_id', models.ManyToManyField(to='databases.album')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
